server:
  port: 20201

spring:

  devtools:
    restart:
      enabled: true
      exclude: static/**
  application:
    name: keledbtools

  datasource:
    username: root
    password: keledb256
    url: jdbc:mysql://localhost:3306/devbase?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

  thymeleaf:
#    mode: LEGACYHTML5
    cache: false