server:
  port: 20201

spring:
  application:
    name: keledbtools

  datasource:
    username: root
#    password: keledb256
    url: jdbc:mysql://172.23.20.101:5688/devbase?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: root123456
    hikari:
      maximum-pool-size: 3
  thymeleaf:
#    mode: LEGACYHTML5
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl